package com.example.beacon;

public class MajorData {
    //this class holds data for all the majors at Wheaton College
    //TODO: Finish putting in majors
    public static String[] wheatonMajors = {
            "Deciding and Discovering",
            "Anthropology",
            "Art",
            "Applied Health Science",
            "Biblical Archaeology",
            "Biblical and Theological Studies",
            "Biochemistry and Molecular Biology",
            "Biology",
            "Business and Economics",
            "Chemistry",
            "Chinese Language and Culture",
            "Christian Formation and Ministry",
            "Classical Languages",
            "Communication",
            "Computer Science",
            "Conservation and Ecological Health",
            "Economics",
            "Education",
            "Engineering",
            "English",
            "Earth and Environmental Science",
            "French",
            "German",
            "Geology",
            "Greek",
            "Hebrew",
            "History",
            "Interdisciplinary Studies",
            "International Relations",
            "Latin",
            "Latin American and Latina/o Studies",
            "Mathematics",
            "Modern and Classical Languages",
            "Music",
            "Neuroscience",
            "Nursing",
            "Philosophy",
            "Physics",
            "Political Science",
            "Psychology",
            "Sociology",
            "Spanish",
            "Urban Studies",
    };
}
